# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_stack_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishedDate',
        ),
    ]
