# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20170719_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
