# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_auto_20170728_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_hired',
            new_name='date_birth',
        ),
    ]
